/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import Controllers.ClaseController;
import Controllers.EntrenadorController;
import DTO.ClaseDTO;
import DTO.EntrenadorDTO;
import java.sql.Date;
import java.time.LocalTime;
import java.util.List;
import javax.swing.JOptionPane;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author bran-
 */
public class VentanaAsignacionClasesGrupales extends javax.swing.JFrame {

    private ClaseController controladorClase;
    private EntrenadorController controlador;
    private Map<String, String> mapaNombreCedula = new HashMap<>();

    /**
     * Creates new form VentanaGestionEntrenadores
     */
    public VentanaAsignacionClasesGrupales() {

        initComponents();
        controladorClase = new ClaseController();
        this.cargarHorasComboBox();
        controlador = new EntrenadorController();
        this.cargarEntrenadoresEnComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtNombreGestionEntrenadores = new javax.swing.JLabel();
        txtEspecialidadGestionEntrenadores = new javax.swing.JLabel();
        txtNombreClase = new javax.swing.JTextField();
        btnAsignarClaseGrupal = new javax.swing.JButton();
        btnAtrasAdminPagos = new javax.swing.JButton();
        cmbEntrenador = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CALENDARIO = new com.toedter.calendar.JDateChooser();
        cmbHora = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Asignación Clases Grupales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Shree Devanagari 714", 0, 18))); // NOI18N

        txtNombreGestionEntrenadores.setFont(new java.awt.Font("Shree Devanagari 714", 1, 14)); // NOI18N
        txtNombreGestionEntrenadores.setText("Nombre Clase :");

        txtEspecialidadGestionEntrenadores.setFont(new java.awt.Font("Shree Devanagari 714", 1, 14)); // NOI18N
        txtEspecialidadGestionEntrenadores.setText("Entrenador:");

        btnAsignarClaseGrupal.setText("Asignar Entrenador");
        btnAsignarClaseGrupal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarClaseGrupalActionPerformed(evt);
            }
        });

        btnAtrasAdminPagos.setText("⤺");
        btnAtrasAdminPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasAdminPagosActionPerformed(evt);
            }
        });

        cmbEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEntrenadorActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Shree Devanagari 714", 1, 14)); // NOI18N
        jLabel1.setText("Fecha de la Clase:");

        jLabel2.setFont(new java.awt.Font("Shree Devanagari 714", 1, 14)); // NOI18N
        jLabel2.setText("Hora de la Clase:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAtrasAdminPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreGestionEntrenadores)
                            .addComponent(txtEspecialidadGestionEntrenadores)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreClase)
                            .addComponent(cmbEntrenador, 0, 121, Short.MAX_VALUE)
                            .addComponent(CALENDARIO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbHora, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btnAsignarClaseGrupal, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAtrasAdminPagos)
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreGestionEntrenadores))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEspecialidadGestionEntrenadores)
                    .addComponent(cmbEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cmbHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(btnAsignarClaseGrupal, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(CALENDARIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAsignarClaseGrupalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarClaseGrupalActionPerformed
        String nombreClase = txtNombreClase.getText();
        String nombreEntrenador = (String) cmbEntrenador.getSelectedItem();
        String entrenadorCedula = mapaNombreCedula.get(nombreEntrenador);
        java.util.Date fechaClase = CALENDARIO.getDate();
        String horaClase = (String) cmbHora.getSelectedItem();

        // Validar que los campos no estén vacíos
        if (nombreClase.isEmpty() || entrenadorCedula == null || fechaClase == null || horaClase == null) {
            JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Convertir java.util.Date a java.sql.Date
        java.util.Date fechaUtil = (java.util.Date) fechaClase;
        java.sql.Date fechaClaseSQL = new java.sql.Date(fechaUtil.getTime());

        // Crear objeto ClaseDTO
        ClaseDTO clase = new ClaseDTO();
        clase.setNombreClase(nombreClase);
        clase.setFechaClase(fechaClaseSQL);
        clase.setHoraClase(horaClase);
        clase.setCedulaEntrenador(entrenadorCedula);

        // Intentar registrar la clase grupal
        boolean registrado = controladorClase.registrarClase(clase);
        if (registrado) {
            JOptionPane.showMessageDialog(this, "Clase grupal registrada con éxito.");
            limpiarCampos(); // Limpia los campos del formulario
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar la clase grupal. Verifica los datos.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnAsignarClaseGrupalActionPerformed

    private void btnAtrasAdminPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasAdminPagosActionPerformed
        VentanaDashBoard panel = new VentanaDashBoard();
        panel.setVisible(true);
        panel.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnAtrasAdminPagosActionPerformed

    private void cmbEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEntrenadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEntrenadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public void limpiarCampos() {
        txtNombreClase.setText("");
        cmbEntrenador.setSelectedIndex(0);
        CALENDARIO.setDate(null);
        cmbHora.setSelectedIndex(0);
    }

    private void cargarHorasComboBox() {
        cmbHora.removeAllItems();
        int horasAlDia = 12; // son 12 horas de clase
        int horaInicio = 7; //inicia a las 7am
        for (int i = horaInicio; i <= (horasAlDia + horaInicio); i++) {
            LocalTime localTime = LocalTime.of(i, 0);
            cmbHora.addItem(localTime.toString());
        }
    }

    private void cargarEntrenadoresEnComboBox() {
        cmbEntrenador.removeAllItems();
        mapaNombreCedula.clear(); // limpiamos el mapa

        List<EntrenadorDTO> listaEntrenadores = controlador.obtenerListaEntrenadores();
        if (listaEntrenadores != null && !listaEntrenadores.isEmpty()) {
            cmbEntrenador.addItem("Seleccionar");
            for (EntrenadorDTO entrenador : listaEntrenadores) {
                String nombre = entrenador.getNombre();
                String cedula = entrenador.getCedula();

                cmbEntrenador.addItem(nombre); // solo el nombre se ve
                mapaNombreCedula.put(nombre, cedula); // guardamos cédula asociada al nombre
            }
        } else {
            cmbEntrenador.addItem("No hay Entrenadores disponibles");
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAsignacionClasesGrupales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAsignacionClasesGrupales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAsignacionClasesGrupales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAsignacionClasesGrupales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAsignacionClasesGrupales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser CALENDARIO;
    private javax.swing.JButton btnAsignarClaseGrupal;
    private javax.swing.JButton btnAtrasAdminPagos;
    private javax.swing.JComboBox<String> cmbEntrenador;
    private javax.swing.JComboBox<String> cmbHora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txtEspecialidadGestionEntrenadores;
    private javax.swing.JTextField txtNombreClase;
    private javax.swing.JLabel txtNombreGestionEntrenadores;
    // End of variables declaration//GEN-END:variables
}
